encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("wiki/", views.index, name="index"),
    path("wiki/newEntry", views.addEntry, name = "addEntry"),
    path("wiki/search", views.searchEntry, name = "search"),
    path("wiki/random", views.randomEntry, name = "random"),
    path("wiki/<str:title>", views.showEntry, name = "showEntry"),
    path("wiki/<str:title>/updated", views.updateEntry, name = "updateEntry"),
    path("wiki/<str:title>/editEntry", views.showEntryToEdit, name = "showEntryToEdit"),
    
    
 
    
    
    
   
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from re import T
from django.http.response import HttpResponse
from encyclopedia import util
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
import random
import markdown2 as md

import encyclopedia


# Takes you to the index page and returns a list of all entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()

    })

# Shows a specific entry. takes an entry title and returns a title and the entry text formated from markdown to html
def showEntry(request, title):
        if(title in util.list_entries()):
            entryText = util.get_entry(title)
            return render(request, "encyclopedia/showEntry.html", {
            "title": title,
            "entry": md.markdown(entryText)})
        else:
            return index(request)
   
    

# Search entry by recieved by get method. If the entry doesnt exists returns a list of similar titles.
def searchEntry(request):
       if request.method == "GET":
            #Get the content of the searchTitle parameter
            title = request.GET["searchTitle"]
            #If the title exists in the list of entries show the entry
            print("search title is  " + title)
            entries = util.list_entries()
        
            if title in entries:
                return showEntry(request, title)
            else:
                likeEntries = []
                
                for i in range(0,len(entries)):
                  if title.lower() in entries[i].lower():
                     likeEntries.append(entries[i])
                return render(request, "encyclopedia/searchEntry.html", {
                     "likeEntries": likeEntries })
       else:
         return index(request)
   
#Adds a new entry
def addEntry(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = "# " + title + "\n\n" +  request.POST["content"]
        entries = util.list_entries()
        if title not in entries and title!="":
            util.save_entry(title, content)
            return showEntry(request,title)
        else:
            return render(request, "The article already exists...")
    else:
        return render(request, "encyclopedia/newEntry.html")

#Displays entry that is going to be edited
def showEntryToEdit(request, title):
        entryText = util.get_entry(title)
        return render(request, "encyclopedia/editEntry.html", {
                     "title": title,
                     "entry": entryText })

#updates a specific entry
def updateEntry(request, title):
    if request.method == "POST":
        content = request.POST["content"]
        util.save_entry(title, content)
        return showEntry(request, title)

# Returns a random entry
def randomEntry(request):
    print("inside randomEntry")
    entries = util.list_entries()
    print("length of entries list is ", len(entries))
    numberOfEntries = len(entries)
    
    #generates a random number between 0 and the entries lenght-1
    randEntry = random.randint(0,numberOfEntries-1)
    
    return showEntry(request, entries[randEntry])

encyclopedia/templates/encyclopedia/editEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Edit Entry
{% endblock %}

{% block body %}
    
<h1> Edit entry</h1>    
<form action="{% url 'entries:updateEntry' title %}" method="POST" >
    {% csrf_token %}
    <label for="text">Title:</label>
    <br>
    <input  type="text" id = "title" name = "title" required placeholder="{{title}}" readonly>
    <br><br>
    <label for="content">Content:</label>
    <textarea class="form-control" rows="18" style="max-width:80%" id="content" name="content" required >{{entry}}</textarea>
<br>
    <input type="submit" value = "Edit entry">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
       
            <li><a href="{% url 'entries:showEntry' entry  %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'entries:search' %}" method="get"  >
                    <input class="search" type="text" name = "searchTitle" placeholder="Search Encyclopedia" style="margin-bottom:10px">
                    <input type="submit" value = "Search" style="margin-bottom:20px">
                </form>
                <div>
                    <a href="{% url 'entries:index' %}">Home</a>
                </div>
                <div>
                    <a href="{%url 'entries:addEntry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{%url 'entries:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add Entry
{% endblock %}

{% block body %}


<h1 style="margin-bottom:10px">Create new page</h1>    
<form  action="{% url 'entries:addEntry' %}" method="POST" >
    {% csrf_token %}
    
    <label for="text">Title:</label>
    <br>
    <input type="text" name = "title" required placeholder="Insert Title" required>
    <br><br>
    <label for="content">Content:</label>
    <br>
    <textarea class="form-control" rows="18" style="max-width:80%" id="content" name="content"  required >   </textarea>
<br>
    <input type="submit" value = "Save">
</form>



{% endblock %}

encyclopedia/templates/encyclopedia/searchEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    
    <ul>
        {% if likeEntries %}
        <h1> Search results</h1>
        {% for entry in likeEntries %}
       
            <li><a href="{% url 'entries:showEntry' entry  %}">{{ entry }}</a></li>
        {% endfor %}
        {% else %}
            <h1> No entries found</h1>
        {% endif%}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/showEntry.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<a href="{% url 'entries:showEntryToEdit' title %}">Edit Entry</a>
<br>
<br>
    {% autoescape off %}
    {{entry}}
    {% endautoescape %}
      

   


{% endblock %}